name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.21, 1.22, '1.23']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install dependencies
      run: go mod download

    - name: Run tests
      run: go test -v ./...

    - name: Build
      run: go build ./cmd/sharkdb

    - name: Run linter
      uses: golangci/golangci-lint-action@v4
      with:
        version: latest

  build-multi-platform:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build for multiple platforms
      run: |
        GOOS=linux GOARCH=amd64 go build -o sharkdb-linux-amd64 ./cmd/sharkdb
        GOOS=darwin GOARCH=amd64 go build -o sharkdb-darwin-amd64 ./cmd/sharkdb
        GOOS=windows GOARCH=amd64 go build -o sharkdb-windows-amd64.exe ./cmd/sharkdb

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: sharkdb-binaries
        path: |
          sharkdb-linux-amd64
          sharkdb-darwin-amd64
          sharkdb-windows-amd64.exe
